version: 2.1
orbs:
  node: circleci/node@4.7
jobs:
  validate:
    docker:
      - image: cimg/node:12.22.7
    steps:
      - run: node --version
      - run: yarn versions
      - checkout
      - run: yarn install
      - run: yarn validate
workflows:
  version: 2
  validate:
    jobs:
      - validate
